-- Procedure Scripts: 

begin
--- This is for QSOP Current Data ----

DELETE FROM EDW1.DW_SF_QSOP_SNAP_F  WHERE DATA_USE_PROCESS  =  'CURRENT' ;

INSERT INTO  EDW1.DW_SF_QSOP_SNAP_F 
(
	SNAPSHOT_TAKEN_DATE_WID
,	SNAPSHOT_TAKEN_DATE
,	SNAPSHOT_QTR
,	SNAPSHOT_WEEK
,	OPPTY_NUMBER
,	OPPTY_NAME
,	OPPTY_CREATED_BY
,	CREATION_DATE
,	OPPTY_OWNER
,	APPROVED_LTR
,	SUBMITTED_LTR
,	LTR
,	PARENT_OPPTY_NUMBER
,	PARENT_OPPTY_NAME
,	LINKED_FLAG
,	REGION
,	MARKET_SEGMENT
,	BU
,	PRODUCT_LINE
,	FINANCIAL_GROUP
,	PART_NUMBER
,	OPPTY_ALL_PARTS
,	STAGE
,	STATUS
,	CUSTOMER
,	END_CUSTOMER
,	BU_APPROVED_DATE
,	APPROVAL_STATUS
,	DESIGN_WIN_DATE
,	APPROVED_DESIGN_WIN_DATE
,	CLOSE_DATE
,	PRODUCTION_DATE
,	APPROVED_PROD_DATE
,	DESIGN_LOSS_DATE
,	DW_FISCAL_YEAR
,	DW_FISCAL_QTR
,	DESIGN_LOSS_YEAR
,	DESIGN_LOSS_QTR
,	PROD_FISCAL_YEAR
,	PROD_FISCAL_QTR
,	CHANNEL
,	INCLUDED_FLAG
,	LIFE_EXPECTANCY
,	CM_ODM
,	ASP_YR1
,	ASP_YR2
,	ASP_YR3
,	ASP_YR4
,	ASP_YR5
,	QTY_YR1
,	QTY_YR2
,	QTY_YR3
,	QTY_YR4
,	QTY_YR5
,	LINE_LEVEL_REVENUE
,	REV_YR1
,	REV_YR2
,	REV_YR3
,	REV_YR4
,	REV_YR5
,	APPROVED_ASP_YR1
,	APPROVED_ASP_YR2
,	APPROVED_ASP_YR3
,	APPROVED_ASP_YR4
,	APPROVED_ASP_YR5
,	APPROVED_QTY_YR1
,	APPROVED_QTY_YR2
,	APPROVED_QTY_YR3
,	APPROVED_QTY_YR4
,	APPROVED_QTY_YR5
,	DW_CONFIRMATION
,	ACKNOWLEDGE_DW_DATE
,	PROTOTYPE_DATE
,	APPROVED_DW_CONFIRMATION
,	DW_CONFIDENCE
,	REASON_FOR_INACTIVE
,	REASON_FOR_LOST_CANCELLED
,	REASON_FOR_EXCLUSION
,	REASON_FOR_LOSS
,	COMMENT_FOR_REASON_FOR_LOSS
,	OPPTY_LEVEL
,	CAR_OEM
,	DATA_USE_PROCESS
,	COMPANY
 ,TYPE 
 ,LTR_LINE_LEVEL 
 ,YEAR_2_LINE_LEVEL_REVENUE 
 ,YEAR_3_LINE_LEVEL_REVENUE 
 ,YEAR_4_LINE_LEVEL_REVENUE 
 ,YEAR_5_LINE_LEVEL_REVENUE 
 ,YEAR_6_LINE_LEVEL_REVENUE 
 ,YEAR_7_LINE_LEVEL_REVENUE 
 ,YEAR_8_LINE_LEVEL_REVENUE
 ,YEAR_9_LINE_LEVEL_REVENUE 
 ,YEAR_10_LINE_LEVEL_REVENUE 
 ,OPPORTUNITY_RECORD_TYPE 
,BU_PRIORITY__C
, HEADER_LTR
,SUB_PRODUCT_LINE
,SEGMENT_NAME
,CREATED_BY_COMPANY
,PRIMARY_OPPTY_OWNER
,DIVISION
,ACCT_BILLING_COUNTRY
,ACCT_BILLING_STATE
,ACCT_CORP_ID_NAME
,OPPTY_ACCT_COUNTRY
,APPLICATION
,APPLICATION_SEGMENT
,APPROVED_HEADER_LTR
,APPROVED_PARENT_OPPTY_LTR
,APPROVER
,DESCRIPTION
,DEVELOPMENT_STAGE
,COMMENTS_FOR_EXEC
,DW_APPROVAL_STATUS_DATE
,IS_ASIC
,IS_AWARDED
,IS_LINKED_PARENT
,NETWORK_PROCESSOR
,REGISTRATION_TYPE
,PROGRAM_NAME
,REG_APPROVAL_STATUS
,CORP_ID_SWITCH_BU_CUST_SEGMENT
,APPROVED_ASP_YR6 
,APPROVED_ASP_YR7 
,APPROVED_ASP_YR8 
,APPROVED_ASP_YR9 
,APPROVED_ASP_YR10
,APPROVED_QTY_YR6 
,APPROVED_QTY_YR7 
,APPROVED_QTY_YR8 
,APPROVED_QTY_YR9 
,APPROVED_QTY_YR10
,QTY_YR6 
,QTY_YR7 
,QTY_YR8 
,QTY_YR9 
,QTY_YR10
,DEVICE
,PRODUCT_FAMILY
,OPPTY_ID
,ASP_YR6
,ASP_YR7
,ASP_YR8
,ASP_YR9
,ASP_YR10
,LINE_ITEM_ID
,ITEM_TYPE_GROUP
,REV_YR6
,REV_YR7
,REV_YR8
,REV_YR9
,REV_YR10
,TOTAL_QUANTITY
,TECHNOLOGY_NODE


)  
SELECT 
	SNAPSHOT_TAKEN_DATE_WID
,	SNAPSHOT_TAKEN_DATE
,	SNAPSHOT_QTR
,	SNAPSHOT_WEEK
,	OPPTY_NUMBER
,	OPPTY_NAME
,	OPPTY_CREATED_BY
,	CREATION_DATE
,	OPPTY_OWNER
,	APPROVED_LTR
,	SUBMITTED_LTR
,	LTR
,	PARENT_OPPTY_NUMBER
,	PARENT_OPPTY_NAME
,	LINKED_FLAG
,	REGION
,	MARKET_SEGMENT
,	BU
,	PRODUCT_LINE
,	FINANCIAL_GROUP
,	PART_NUMBER
,	OPPTY_ALL_PARTS
,	STAGE
,	STATUS
,	CUSTOMER
,	END_CUSTOMER
,	BU_APPROVED_DATE
,	APPROVAL_STATUS
,	DESIGN_WIN_DATE
,	APPROVED_DESIGN_WIN_DATE
,	CLOSE_DATE
,	PRODUCTION_DATE
,	APPROVED_PROD_DATE
,	DESIGN_LOSS_DATE
,	DW_FISCAL_YEAR
,	DW_FISCAL_QTR
,	DESIGN_LOSS_YEAR
,	DESIGN_LOSS_QTR
,	PROD_FISCAL_YEAR
,	PROD_FISCAL_QTR
,	CHANNEL
,	INCLUDED_FLAG
,	LIFE_EXPECTANCY
,	CM_ODM
,	ASP_YR1
,	ASP_YR2
,	ASP_YR3
,	ASP_YR4
,	ASP_YR5
,	QTY_YR1
,	QTY_YR2
,	QTY_YR3
,	QTY_YR4
,	QTY_YR5
,	LINE_LEVEL_REVENUE
,	REV_YR1
,	REV_YR2
,	REV_YR3
,	REV_YR4
,	REV_YR5
,	APPROVED_ASP_YR1
,	APPROVED_ASP_YR2
,	APPROVED_ASP_YR3
,	APPROVED_ASP_YR4
,	APPROVED_ASP_YR5
,	APPROVED_QTY_YR1
,	APPROVED_QTY_YR2
,	APPROVED_QTY_YR3
,	APPROVED_QTY_YR4
,	APPROVED_QTY_YR5
,	DW_CONFIRMATION
,	ACKNOWLEDGE_DW_DATE
,	PROTOTYPE_DATE
,	APPROVED_DW_CONFIRMATION
,	DW_CONFIDENCE
,	REASON_FOR_INACTIVE
,	REASON_FOR_LOST_CANCELLED
,	REASON_FOR_EXCLUSION
,	REASON_FOR_LOSS
,	COMMENT_FOR_REASON_FOR_LOSS
,	OPPTY_LEVEL
,	CAR_OEM
,                    DATA_USE_PROCESS
,	NVL(COMPANY,'Cavium')  --- null Company values replaced with Company = Cavium
 ,TYPE 
 ,LTR_LINE_LEVEL 
 ,YEAR_2_LINE_LEVEL_REVENUE 
 ,YEAR_3_LINE_LEVEL_REVENUE 
 ,YEAR_4_LINE_LEVEL_REVENUE 
 ,YEAR_5_LINE_LEVEL_REVENUE 
 ,YEAR_6_LINE_LEVEL_REVENUE 
 ,YEAR_7_LINE_LEVEL_REVENUE 
 ,YEAR_8_LINE_LEVEL_REVENUE
 ,YEAR_9_LINE_LEVEL_REVENUE 
 ,YEAR_10_LINE_LEVEL_REVENUE 
 ,OPPORTUNITY_RECORD_TYPE 
,BU_PRIORITY__C
,HEADER_LTR
,SUB_PRODUCT_LINE
,SEGMENT_NAME
,CREATED_BY_COMPANY
,PRIMARY_OPPTY_OWNER
,DIVISION
,ACCT_BILLING_COUNTRY
,ACCT_BILLING_STATE
,ACCT_CORP_ID_NAME
,OPPTY_ACCT_COUNTRY
,APPLICATION
,APPLICATION_SEGMENT
,APPROVED_HEADER_LTR
,APPROVED_PARENT_OPPTY_LTR
,APPROVER
,DESCRIPTION
,DEVELOPMENT_STAGE
,COMMENTS_FOR_EXEC
,DW_APPROVAL_STATUS_DATE
,IS_ASIC
,IS_AWARDED
,IS_LINKED_PARENT
,NETWORK_PROCESSOR
,REGISTRATION_TYPE
,PROGRAM_NAME
,REG_APPROVAL_STATUS
,CORP_ID_SWITCH_BU_CUST_SEGMENT
,APPROVED_ASP_YR6 
,APPROVED_ASP_YR7 
,APPROVED_ASP_YR8 
,APPROVED_ASP_YR9 
,APPROVED_ASP_YR10
,APPROVED_QTY_YR6 
,APPROVED_QTY_YR7 
,APPROVED_QTY_YR8 
,APPROVED_QTY_YR9 
,APPROVED_QTY_YR10
,QTY_YR6 
,QTY_YR7 
,QTY_YR8 
,QTY_YR9 
,QTY_YR10
,DEVICE
,PRODUCT_FAMILY
,OPPTY_ID
,ASP_YR6
,ASP_YR7
,ASP_YR8
,ASP_YR9
,ASP_YR10
,LINE_ITEM_ID
,ITEM_TYPE_GROUP
,REV_YR6
,REV_YR7
,REV_YR8
,REV_YR9
,REV_YR10
,TOTAL_QUANTITY
,TECHNOLOGY_NODE

FROM EDW1.DW_SF_QSOP_F_V ;

UPDATE  EDW1.DW_SF_QSOP_SNAP_F  SET DATA_USE_PROCESS = 'CURRENT' WHERE DATA_USE_PROCESS = 'CURRENT_OPPTY_DATA'  ;

UPDATE EDW1.DW_SF_QSOP_SNAP_F SET CURR_YEAR = (select calendar_year from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL' and calendar_id = to_char(sysdate,'YYYYMMDD'))
, PREV_YEAR = (select calendar_year-1 from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL' and calendar_id = to_char(sysdate,'YYYYMMDD')) , 
CURR_QTR = (select quarter_name from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL' and calendar_id = to_char(sysdate,'YYYYMMDD')),
PREV_QTR = (select case  WHEN CALENDAR_QUARTER_AGO_WID = 4 then calendar_year-1||'-Q'||CALENDAR_QUARTER_AGO_WID ELSE calendar_year||'-Q'||CALENDAR_QUARTER_AGO_WID END
from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL' and calendar_id = to_char(sysdate,'YYYYMMDD')) WHERE DATA_USE_PROCESS = 'CURRENT';

----- Past Qtr Active Oppty LTR set to zero
UPDATE EDW1.DW_SF_QSOP_SNAP_F SET LTR = 0 WHERE DATA_USE_PROCESS ='CURRENT' and upper(STATUS) = 'ACTIVE' and  DW_FISCAL_QTR < 
(select QUARTER_NAME from edw1.dw_day_d where calendar_type ='MVL_FISCAL_CAL' and calendar_id = to_char(sysdate,'YYYYMMDD'));
---- Exceptions update on OPPTY --- one time update
update EDW1.DW_SF_QSOP_SNAP_F set company = 'Cavium' where DATA_USE_PROCESS = 'CURRENT' and OPPTY_NUMBER = '31102';

end;


Procedure 2

Declare
--- This is for updating  MILLION_PLUS_HEADER_LTR_FLAG in current data for FY2020 onwards ----
cursor C_ONE_MILLION_OPPTY IS
select oppty_number,SUM(LTR) from edw1.dw_sf_qsop_snap_f  where data_use_process = 'CURRENT' and included_flag = 'TRUE' and DW_FISCAL_YEAR > 2019 and status != 'Lost'
group by oppty_number having sum(LTR) < 1000000;
begin
    FOR REC in C_ONE_MILLION_OPPTY
      LOOP
        UPDATE edw1.dw_sf_qsop_snap_f SET MILLION_PLUS_HEADER_LTR_FLAG ='N' WHERE oppty_number = REC.oppty_number and included_flag = 'TRUE'and data_use_process = 'CURRENT'; 
      END LOOP;
end;


 -- procedure 3

--Creating Procedure to update Primary Opportunity Owner Sales Region and Sub Region

DECLARE
CURSOR C_USER_REGION_DETAILS IS 
    SELECT  T.OPPORTUNITYID ,T.ID, u.DIVISION ,U.NAME, U.SALES_TERRITORY__C
    from edw1.DW_SF_OPPTEAM_F T inner join edw1.dw_sf_user_d U on T.userid=U.userid
                 where T.teammemberrole = 'MRVL Primary Oppty Owner' ORDER BY  T.row_wid;
BEGIN
    FOR REC in C_USER_REGION_DETAILS
      LOOP
        UPDATE EDW1.dw_sf_qsop_snap_f SET SALES_REGION= REC.SALES_TERRITORY__C, SUB_REGION = REC.DIVISION
        WHERE OPPTY_ID = REC.OPPORTUNITYID and DATA_USE_PROCESS = 'CURRENT';
      END LOOP;
END;


-- procedure 4
------- Snapshot Procedure -------
DECLARE
V_DATA_USE_PROCESS varchar2(30); ----- Set variable to the week;
V_QTR_LAST_DATE VARCHAR2(30);
V_CURRENT_DATE VARCHAR2(30);
V_PST_TIME TIMESTAMP;

BEGIN

SELECT FROM_TZ(CAST( sysdate as timestamp), 'Asia/Singapore')AT TIME ZONE 'America/Los_Angeles' into V_PST_TIME FROM DUAL;

--V_PST_TIME := to_timestamp('2021-05-01 01:00','YYYY-MM-DD HH24:MI'); -- for test

SELECT CALENDAR_QUARTER_END_DATE_WID into V_QTR_LAST_DATE from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL'  
and calendar_id = (select to_number(to_char(trunc(V_PST_TIME),'YYYYMMDD')) from dual);

SELECT CALENDAR_ID   into V_CURRENT_DATE from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL' 
and calendar_id = (select to_number(to_char(trunc(V_PST_TIME),'YYYYMMDD')) from dual);

IF V_QTR_LAST_DATE = V_CURRENT_DATE   THEN
    V_CURRENT_DATE := V_CURRENT_DATE +1;
    select (quarter_name ||' DAY 1') into V_DATA_USE_PROCESS from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL'  and calendar_id = V_CURRENT_DATE;
ELSE
    select (quarter_name ||' WK-'||CALENDAR_QUARTER_WEEK) into V_DATA_USE_PROCESS from edw1.dw_day_d where calendar_type = 'MVL_FISCAL_CAL'  and calendar_id = (select
     to_number(to_char(trunc(sysdate),'YYYYMMDD')) from dual);
END IF; 

DELETE FROM EDW1.DW_SF_QSOP_SNAP_F where  trim(DATA_USE_PROCESS) = V_DATA_USE_PROCESS ; --- Delete if the existing same Qtr snapshot is available

INSERT INTO EDW1.DW_SF_QSOP_SNAP_F
(
	SNAPSHOT_TAKEN_DATE_WID
,	SNAPSHOT_TAKEN_DATE
,	SNAPSHOT_QTR
,	SNAPSHOT_WEEK
,	OPPTY_NUMBER
,	OPPTY_NAME
,	OPPTY_CREATED_BY
,	CREATION_DATE
,	OPPTY_OWNER
,	APPROVED_LTR
,	SUBMITTED_LTR
,	LTR
,	PARENT_OPPTY_NUMBER
,	PARENT_OPPTY_NAME
,	LINKED_FLAG
,	REGION
,	MARKET_SEGMENT
,	BU
,	PRODUCT_LINE
,	FINANCIAL_GROUP
,	PART_NUMBER
,	OPPTY_ALL_PARTS
,	STAGE
,	STATUS
,	CUSTOMER
,	END_CUSTOMER
,	BU_APPROVED_DATE
,	APPROVAL_STATUS
,	DESIGN_WIN_DATE
,	APPROVED_DESIGN_WIN_DATE
,	CLOSE_DATE
,	PRODUCTION_DATE
,	APPROVED_PROD_DATE
,	DESIGN_LOSS_DATE
,	DW_FISCAL_YEAR
,	DW_FISCAL_QTR
,	DESIGN_LOSS_YEAR
,	DESIGN_LOSS_QTR
,	PROD_FISCAL_YEAR
,	PROD_FISCAL_QTR
,	CHANNEL
,	INCLUDED_FLAG
,	LIFE_EXPECTANCY
,	CM_ODM
,	ASP_YR1
,	ASP_YR2
,	ASP_YR3
,	ASP_YR4
,	ASP_YR5
,	QTY_YR1
,	QTY_YR2
,	QTY_YR3
,	QTY_YR4
,	QTY_YR5
,	LINE_LEVEL_REVENUE
,	REV_YR1
,	REV_YR2
,	REV_YR3
,	REV_YR4
,	REV_YR5
,	APPROVED_ASP_YR1
,	APPROVED_ASP_YR2
,	APPROVED_ASP_YR3
,	APPROVED_ASP_YR4
,	APPROVED_ASP_YR5
,	APPROVED_QTY_YR1
,	APPROVED_QTY_YR2
,	APPROVED_QTY_YR3
,	APPROVED_QTY_YR4
,	APPROVED_QTY_YR5
,	DW_CONFIRMATION
,	ACKNOWLEDGE_DW_DATE
,	PROTOTYPE_DATE
,	APPROVED_DW_CONFIRMATION
,	DW_CONFIDENCE
,	REASON_FOR_INACTIVE
,	REASON_FOR_LOST_CANCELLED
,	REASON_FOR_EXCLUSION
,	REASON_FOR_LOSS
,	COMMENT_FOR_REASON_FOR_LOSS
,	OPPTY_LEVEL
,	CAR_OEM
,	DATA_USE_PROCESS
,	COMPANY
,	CURR_YEAR
,	PREV_YEAR
,	PREV_QTR
,	TYPE
,	LTR_LINE_LEVEL
,	YEAR_2_LINE_LEVEL_REVENUE
,	YEAR_3_LINE_LEVEL_REVENUE
,	YEAR_4_LINE_LEVEL_REVENUE
,	YEAR_5_LINE_LEVEL_REVENUE
,	YEAR_6_LINE_LEVEL_REVENUE
,	YEAR_7_LINE_LEVEL_REVENUE
,	YEAR_8_LINE_LEVEL_REVENUE
,	YEAR_9_LINE_LEVEL_REVENUE
,	YEAR_10_LINE_LEVEL_REVENUE
,	OPPORTUNITY_RECORD_TYPE
,       BU_PRIORITY__C
, 	HEADER_LTR
,       CURR_QTR,MILLION_PLUS_HEADER_LTR_FLAG,
SUB_PRODUCT_LINE, SEGMENT_NAME, CREATED_BY_COMPANY, PRIMARY_OPPTY_OWNER
,DIVISION
,ACCT_BILLING_COUNTRY
,ACCT_BILLING_STATE
,ACCT_CORP_ID_NAME
,OPPTY_ACCT_COUNTRY
,APPLICATION
,APPLICATION_SEGMENT
,APPROVED_HEADER_LTR
,APPROVED_PARENT_OPPTY_LTR
,APPROVER
,DESCRIPTION
,DEVELOPMENT_STAGE
,COMMENTS_FOR_EXEC
,DW_APPROVAL_STATUS_DATE
,IS_ASIC
,IS_AWARDED
,IS_LINKED_PARENT
,NETWORK_PROCESSOR
,REGISTRATION_TYPE
,PROGRAM_NAME
,REG_APPROVAL_STATUS
,CORP_ID_SWITCH_BU_CUST_SEGMENT
,APPROVED_ASP_YR6 
,APPROVED_ASP_YR7 
,APPROVED_ASP_YR8 
,APPROVED_ASP_YR9 
,APPROVED_ASP_YR10
,APPROVED_QTY_YR6 
,APPROVED_QTY_YR7 
,APPROVED_QTY_YR8 
,APPROVED_QTY_YR9 
,APPROVED_QTY_YR10
,QTY_YR6 
,QTY_YR7 
,QTY_YR8 
,QTY_YR9 
,QTY_YR10
,DEVICE
,PRODUCT_FAMILY
,OPPTY_ID
,SALES_REGION
,SUB_REGION
,ASP_YR6
,ASP_YR7
,ASP_YR8
,ASP_YR9
,ASP_YR10
,LINE_ITEM_ID
,ITEM_TYPE_GROUP
,REV_YR6
,REV_YR7
,REV_YR8
,REV_YR9
,REV_YR10
,TOTAL_QUANTITY
,TECHNOLOGY_NODE

)
select 
	SNAPSHOT_TAKEN_DATE_WID
,	SNAPSHOT_TAKEN_DATE
,	SNAPSHOT_QTR
,	SNAPSHOT_WEEK
,	OPPTY_NUMBER
,	OPPTY_NAME
,	OPPTY_CREATED_BY
,	CREATION_DATE
,	OPPTY_OWNER
,	APPROVED_LTR
,	SUBMITTED_LTR
,	LTR
,	PARENT_OPPTY_NUMBER
,	PARENT_OPPTY_NAME
,	LINKED_FLAG
,	REGION
,	MARKET_SEGMENT
,	BU
,	PRODUCT_LINE
,	FINANCIAL_GROUP
,	PART_NUMBER
,	OPPTY_ALL_PARTS
,	STAGE
,	STATUS
,	CUSTOMER
,	END_CUSTOMER
,	BU_APPROVED_DATE
,	APPROVAL_STATUS
,	DESIGN_WIN_DATE
,	APPROVED_DESIGN_WIN_DATE
,	CLOSE_DATE
,	PRODUCTION_DATE
,	APPROVED_PROD_DATE
,	DESIGN_LOSS_DATE
,	DW_FISCAL_YEAR
,	DW_FISCAL_QTR
,	DESIGN_LOSS_YEAR
,	DESIGN_LOSS_QTR
,	PROD_FISCAL_YEAR
,	PROD_FISCAL_QTR
,	CHANNEL
,	INCLUDED_FLAG
,	LIFE_EXPECTANCY
,	CM_ODM
,	ASP_YR1
,	ASP_YR2
,	ASP_YR3
,	ASP_YR4
,	ASP_YR5
,	QTY_YR1
,	QTY_YR2
,	QTY_YR3
,	QTY_YR4
,	QTY_YR5
,	LINE_LEVEL_REVENUE
,	REV_YR1
,	REV_YR2
,	REV_YR3
,	REV_YR4
,	REV_YR5
,	APPROVED_ASP_YR1
,	APPROVED_ASP_YR2
,	APPROVED_ASP_YR3
,	APPROVED_ASP_YR4
,	APPROVED_ASP_YR5
,	APPROVED_QTY_YR1
,	APPROVED_QTY_YR2
,	APPROVED_QTY_YR3
,	APPROVED_QTY_YR4
,	APPROVED_QTY_YR5
,	DW_CONFIRMATION
,	ACKNOWLEDGE_DW_DATE
,	PROTOTYPE_DATE
,	APPROVED_DW_CONFIRMATION
,	DW_CONFIDENCE
,	REASON_FOR_INACTIVE
,	REASON_FOR_LOST_CANCELLED
,	REASON_FOR_EXCLUSION
,	REASON_FOR_LOSS
,	COMMENT_FOR_REASON_FOR_LOSS
,	OPPTY_LEVEL
,	CAR_OEM
,	V_DATA_USE_PROCESS
,	COMPANY
,	CURR_YEAR
,	PREV_YEAR
,	PREV_QTR
,	TYPE
,	LTR_LINE_LEVEL
,	YEAR_2_LINE_LEVEL_REVENUE
,	YEAR_3_LINE_LEVEL_REVENUE
,	YEAR_4_LINE_LEVEL_REVENUE
,	YEAR_5_LINE_LEVEL_REVENUE
,	YEAR_6_LINE_LEVEL_REVENUE
,	YEAR_7_LINE_LEVEL_REVENUE
,	YEAR_8_LINE_LEVEL_REVENUE
,	YEAR_9_LINE_LEVEL_REVENUE
,	YEAR_10_LINE_LEVEL_REVENUE
,	OPPORTUNITY_RECORD_TYPE
,       BU_PRIORITY__C
,	HEADER_LTR
,       CURR_QTR,MILLION_PLUS_HEADER_LTR_FLAG,
SUB_PRODUCT_LINE, SEGMENT_NAME, CREATED_BY_COMPANY, PRIMARY_OPPTY_OWNER

,DIVISION
,ACCT_BILLING_COUNTRY
,ACCT_BILLING_STATE
,ACCT_CORP_ID_NAME
,OPPTY_ACCT_COUNTRY
,APPLICATION
,APPLICATION_SEGMENT
,APPROVED_HEADER_LTR
,APPROVED_PARENT_OPPTY_LTR
,APPROVER
,DESCRIPTION
,DEVELOPMENT_STAGE
,COMMENTS_FOR_EXEC
,DW_APPROVAL_STATUS_DATE
,IS_ASIC
,IS_AWARDED
,IS_LINKED_PARENT
,NETWORK_PROCESSOR
,REGISTRATION_TYPE
,PROGRAM_NAME
,REG_APPROVAL_STATUS
,CORP_ID_SWITCH_BU_CUST_SEGMENT
,APPROVED_ASP_YR6 
,APPROVED_ASP_YR7 
,APPROVED_ASP_YR8 
,APPROVED_ASP_YR9 
,APPROVED_ASP_YR10
,APPROVED_QTY_YR6 
,APPROVED_QTY_YR7 
,APPROVED_QTY_YR8 
,APPROVED_QTY_YR9 
,APPROVED_QTY_YR10
,QTY_YR6 
,QTY_YR7 
,QTY_YR8 
,QTY_YR9 
,QTY_YR10
,DEVICE
,PRODUCT_FAMILY
,OPPTY_ID
,SALES_REGION
,SUB_REGION
,ASP_YR6
,ASP_YR7
,ASP_YR8
,ASP_YR9
,ASP_YR10
,LINE_ITEM_ID
,ITEM_TYPE_GROUP
,REV_YR6
,REV_YR7
,REV_YR8
,REV_YR9
,REV_YR10
,TOTAL_QUANTITY
,TECHNOLOGY_NODE

from  EDW1.DW_SF_QSOP_SNAP_F where   DATA_USE_PROCESS ='CURRENT';
END;
----------------END OF SNAPSHOT ------


-- procedure 5

DECLARE
CURSOR C_PARENT_OPPTY_DATA IS
SELECT 
P.LINE_ITEM_ID,
TO_CHAR(nvl(P.parent_oppty_number,P.oppty_number)) PARENT_OPPTY_NUMBER,
P.OPPTY_NUMBER,
P.TYPE,
P.OPPTY_NAME,
P.MILLION_PLUS_HEADER_LTR_FLAG,
P.MILLION_PLUS_HEADER_LTR_FLAG PARENT_ONE_MIL_LTR_PLUS_FLAG,
P.INCLUDED_FLAG,
P.INCLUDED_FLAG PARENT_INCLUDED_FLAG,
P.DESIGN_WIN_DATE,
P.DW_FISCAL_YEAR,
P.DW_FISCAL_QTR,
P.DW_FISCAL_YEAR PARENT_DW_FY_YEAR ,
P.DW_FISCAL_QTR PARENT_DW_FY_QTR,
P.PRODUCTION_DATE,
P.PROD_FISCAL_YEAR,
P.PROD_FISCAL_QTR,
P.PROD_FISCAL_YEAR PARENT_PROD_FISCAL_YEAR,
P.PROD_FISCAL_QTR PARENT_PROD_FISCAL_QTR,
P.MARKET_SEGMENT,
P.REGION,
P.REGION PARENT_REGION,
P.STAGE,
P.STAGE PARENT_STAGE,
P.STATUS,
P.STATUS PARENT_STATUS,
P.BU,
P.DIVISION,
P.PRODUCT_LINE,
P.SUB_PRODUCT_LINE,
P.FINANCIAL_GROUP,
P.PART_NUMBER,
P.PRODUCT_FAMILY,
P.DEVICE,
P.REASON_FOR_EXCLUSION,
P.LTR,
P.PRIMARY_OPPTY_OWNER,
P.CUSTOMER,
P.END_CUSTOMER SOURCE_END_CUSTOMER,
' ' as TIER1_CUSTOMER,
P.DW_CONFIDENCE,
P.PROGRAM_NAME,
P.APPLICATION_SEGMENT,
P.NETWORK_PROCESSOR,
P.DEVELOPMENT_STAGE,
P.ITEM_TYPE_GROUP,
P.OPPTY_ID,
RTRIM(REGEXP_REPLACE((select listagg(customer,';') within GROUP(order by oppty_number) from edw1.dw_sf_qsop_snap_f where type = 'Child' and 
parent_oppty_number = P.Oppty_number and data_use_process ='CURRENT' 
and included_flag = 'TRUE' and status in ('Won','Active')),'([^;]*)(;\1)+($|;)', 
       '\1\3'),  ';') TIER1_CUSTOMER_FILTER,
         RTRIM(REGEXP_REPLACE((select listagg(REGION,';') within GROUP(order by oppty_number) from edw1.dw_sf_qsop_snap_f where type = 'Child' and 
parent_oppty_number = P.Oppty_number and data_use_process ='CURRENT' 
and included_flag = 'TRUE' and status in ('Won','Active')),'([^;]*)(;\1)+($|;)', '\1\3'),';') TIER1_REGION
from EDW1.DW_SF_QSOP_SNAP_F P
where P.TYPE ='Parent'AND P.data_use_process = 'CURRENT'
AND (BU = 'Automotive' or Market_segment = 'Automotive');

CURSOR C_CHILD_OPPTY_DATA is 
SELECT
C.LINE_ITEM_ID,
TO_CHAR(C.PARENT_OPPTY_NUMBER) PARENT_OPPTY_NUMBER,
C.OPPTY_NUMBER,
C.TYPE,
C.OPPTY_NAME,
C.MILLION_PLUS_HEADER_LTR_FLAG,
C.INCLUDED_FLAG,
C.DESIGN_WIN_DATE,
C.DW_FISCAL_YEAR,
C.DW_FISCAL_QTR,
C.DW_FISCAL_YEAR PARENT_DW_FY_YEAR ,
C.DW_FISCAL_QTR PARENT_DW_FY_QTR,
C.PRODUCTION_DATE,
C.PROD_FISCAL_YEAR,
C.PROD_FISCAL_QTR,
C.PROD_FISCAL_YEAR PARENT_PROD_FISCAL_YEAR,
C.PROD_FISCAL_QTR PARENT_PROD_FISCAL_QTR,
C.MARKET_SEGMENT,
C.REGION,
C. REGION PARENT_REGION,
C.STAGE,
C.STAGE PARENT_STAGE,
C.STATUS,
C.STATUS PARENT_STATUS,
C.BU,
C.DIVISION,
C.PRODUCT_LINE,
C.SUB_PRODUCT_LINE,
C.FINANCIAL_GROUP,
C.PART_NUMBER,
C.PRODUCT_FAMILY,
C.DEVICE,
C.REASON_FOR_EXCLUSION,
C.LTR,
C.PRIMARY_OPPTY_OWNER,
C.END_CUSTOMER  CUSTOMER,
C.END_CUSTOMER  SOURCE_END_CUSTOMER,
C.CUSTOMER TIER1_CUSTOMER,
C.DW_CONFIDENCE,
C.PROGRAM_NAME,
C.APPLICATION_SEGMENT,
C.NETWORK_PROCESSOR,
C.DEVELOPMENT_STAGE,
C.ITEM_TYPE_GROUP,
C.CUSTOMER TIER1_CUSTOMER_FILTER,
C.REGION TIER1_REGION,
C.OPPTY_ID
from EDW1.DW_SF_QSOP_SNAP_F C
where C.TYPE ='Child' AND C.data_use_process = 'CURRENT' AND (BU = 'Automotive' or Market_segment = 'Automotive');

CURSOR C_PARENT_OPPTY_ATTRIBUTES IS
SELECT DISTINCT
        OPPTY_NUMBER,
        REGION,
        STAGE,
        STATUS,
        MILLION_PLUS_HEADER_LTR_FLAG,
        DW_FISCAL_YEAR,
        DW_FISCAL_QTR,
        INCLUDED_FLAG,
        PROD_FISCAL_YEAR,
        PROD_FISCAL_QTR
    FROM
        EDW1.DW_SF_QSOP_SNAP_F
    WHERE
        TYPE ='Parent'AND data_use_process = 'CURRENT' AND (BU = 'Automotive' or Market_segment = 'Automotive') AND status IN ('Active','Won') 
        AND included_flag = 'TRUE';

TYPE OPPTY_RECORD IS TABLE OF C_PARENT_OPPTY_DATA%rowtype;
TYPE CHILD_OPPTY_RECORD IS TABLE OF C_CHILD_OPPTY_DATA%rowtype;
TYPE PARENT_OPPTY_FILTERS IS TABLE OF C_PARENT_OPPTY_ATTRIBUTES%rowtype;

OPPTY_BULK OPPTY_RECORD;
UPDATE_BULK PARENT_OPPTY_FILTERS;
CHILD_OPPTY_BULK CHILD_OPPTY_RECORD;

BEGIN
DELETE FROM EDW1.DW_SF_PARENT_CHILD_OPPTY_F;


OPEN C_PARENT_OPPTY_DATA;
FETCH C_PARENT_OPPTY_DATA BULK COLLECT INTO OPPTY_BULK;
CLOSE C_PARENT_OPPTY_DATA;

IF OPPTY_BULK.count > 0 THEN
    FOR i IN OPPTY_BULK.first..OPPTY_BULK.last 
    LOOP
    INSERT INTO EDW1.DW_SF_PARENT_CHILD_OPPTY_F(
    LINE_ITEM_ID,
    PARENT_OPPTY_NUMBER,
    OPPTY_NUMBER,
    TYPE,
    OPPTY_NAME,
    MILLION_PLUS_HEADER_LTR_FLAG,
    PARENT_ONE_MIL_LTR_PLUS_FLAG,
    INCLUDED_FLAG,
    PARENT_INCLUDED_FLAG,
    DESIGN_WIN_DATE,
    DW_FISCAL_YEAR,
    DW_FISCAL_QTR,
    PARENT_DW_FY_YEAR ,
    PARENT_DW_FY_QTR,
    PRODUCTION_DATE,
    PROD_FISCAL_YEAR,
    PROD_FISCAL_QTR,
    PARENT_PROD_FISCAL_YEAR,
    PARENT_PROD_FISCAL_QTR,
    MARKET_SEGMENT,
    REGION,
    PARENT_REGION,
    STAGE,
    PARENT_STAGE,
    STATUS,
    PARENT_STATUS,
    BU,
    DIVISION,
    PRODUCT_LINE,
    SUB_PRODUCT_LINE,
    FINANCIAL_GROUP,
    PART_NUMBER,
    PRODUCT_FAMILY,
    DEVICE,
    REASON_FOR_EXCLUSION,
    LTR,
    PRIMARY_OPPTY_OWNER,
    CUSTOMER,
    SOURCE_END_CUSTOMER,
    TIER1_CUSTOMER,
    DW_CONFIDENCE,
    PROGRAM_NAME,
    APPLICATION_SEGMENT,
    NETWORK_PROCESSOR,
    DEVELOPMENT_STAGE,
    ITEM_TYPE_GROUP,
    OPPTY_ID,
    TIER1_CUSTOMER_FILTER,
    TIER1_REGION)
    VALUES 
    (OPPTY_BULK(i).LINE_ITEM_ID,
    OPPTY_BULK(i).PARENT_OPPTY_NUMBER,
    OPPTY_BULK(i).OPPTY_NUMBER,
    OPPTY_BULK(i).TYPE,
    OPPTY_BULK(i).OPPTY_NAME,
    OPPTY_BULK(i).MILLION_PLUS_HEADER_LTR_FLAG,
    OPPTY_BULK(i).PARENT_ONE_MIL_LTR_PLUS_FLAG,
    OPPTY_BULK(i).INCLUDED_FLAG,
    OPPTY_BULK(i).PARENT_INCLUDED_FLAG,
    OPPTY_BULK(i).DESIGN_WIN_DATE,
    OPPTY_BULK(i).DW_FISCAL_YEAR,
    OPPTY_BULK(i).DW_FISCAL_QTR,
    OPPTY_BULK(i).PARENT_DW_FY_YEAR,
    OPPTY_BULK(i).PARENT_DW_FY_QTR,
    OPPTY_BULK(i).PRODUCTION_DATE,
    OPPTY_BULK(i).PROD_FISCAL_YEAR,
    OPPTY_BULK(i).PROD_FISCAL_QTR,
    OPPTY_BULK(i).PARENT_PROD_FISCAL_YEAR,
    OPPTY_BULK(i).PARENT_PROD_FISCAL_QTR,
    OPPTY_BULK(i).MARKET_SEGMENT,
    OPPTY_BULK(i).REGION,
    OPPTY_BULK(i).PARENT_REGION,
    OPPTY_BULK(i).STAGE,
    OPPTY_BULK(i).PARENT_STAGE,
    OPPTY_BULK(i).STATUS,
    OPPTY_BULK(i).PARENT_STATUS,
    OPPTY_BULK(i).BU,
    OPPTY_BULK(i).DIVISION,
    OPPTY_BULK(i).PRODUCT_LINE,
    OPPTY_BULK(i).SUB_PRODUCT_LINE,
    OPPTY_BULK(i).FINANCIAL_GROUP,
    OPPTY_BULK(i).PART_NUMBER,
    OPPTY_BULK(i).PRODUCT_FAMILY,
    OPPTY_BULK(i).DEVICE,
    OPPTY_BULK(i).REASON_FOR_EXCLUSION,
    OPPTY_BULK(i).LTR,
    OPPTY_BULK(i).PRIMARY_OPPTY_OWNER,
    OPPTY_BULK(i).CUSTOMER,
    OPPTY_BULK(i).SOURCE_END_CUSTOMER,
    OPPTY_BULK(i).TIER1_CUSTOMER,
    OPPTY_BULK(i).DW_CONFIDENCE,
    OPPTY_BULK(i).PROGRAM_NAME,
    OPPTY_BULK(i).APPLICATION_SEGMENT,
    OPPTY_BULK(i).NETWORK_PROCESSOR,
    OPPTY_BULK(i).DEVELOPMENT_STAGE,
    OPPTY_BULK(i).ITEM_TYPE_GROUP,
    OPPTY_BULK(i).OPPTY_ID,
    OPPTY_BULK(i).TIER1_CUSTOMER_FILTER,
    OPPTY_BULK(i).TIER1_REGION);
    END LOOP;
    END IF;
commit; 



OPEN C_CHILD_OPPTY_DATA;
FETCH C_CHILD_OPPTY_DATA BULK COLLECT INTO CHILD_OPPTY_BULK;
CLOSE C_CHILD_OPPTY_DATA;

IF CHILD_OPPTY_BULK.count > 0 THEN
    FOR i IN CHILD_OPPTY_BULK.first..CHILD_OPPTY_BULK.last 
    LOOP
    INSERT INTO EDW1.DW_SF_PARENT_CHILD_OPPTY_F(
    LINE_ITEM_ID,
    PARENT_OPPTY_NUMBER,
    OPPTY_NUMBER,
    TYPE,
    OPPTY_NAME,
    MILLION_PLUS_HEADER_LTR_FLAG,
    INCLUDED_FLAG,
    DESIGN_WIN_DATE,
    DW_FISCAL_YEAR,
    DW_FISCAL_QTR,
    PARENT_DW_FY_YEAR ,
    PARENT_DW_FY_QTR,
    PRODUCTION_DATE,
    PROD_FISCAL_YEAR,
    PROD_FISCAL_QTR,
    PARENT_PROD_FISCAL_YEAR,
    PARENT_PROD_FISCAL_QTR,
    MARKET_SEGMENT,
    REGION,
    PARENT_REGION,
    STAGE,
    PARENT_STAGE,
    STATUS,
    PARENT_STATUS,
    BU,
    DIVISION,
    PRODUCT_LINE,
    SUB_PRODUCT_LINE,
    FINANCIAL_GROUP,
    PART_NUMBER,
    PRODUCT_FAMILY,
    DEVICE,
    REASON_FOR_EXCLUSION,
    LTR,
    PRIMARY_OPPTY_OWNER,
    CUSTOMER,
    SOURCE_END_CUSTOMER,
    TIER1_CUSTOMER,
    DW_CONFIDENCE,
    PROGRAM_NAME,
    APPLICATION_SEGMENT,
    NETWORK_PROCESSOR,
    DEVELOPMENT_STAGE,
    ITEM_TYPE_GROUP,
    OPPTY_ID,
    TIER1_CUSTOMER_FILTER,
    TIER1_REGION)
    VALUES 
    (CHILD_OPPTY_BULK(i).LINE_ITEM_ID,
    CHILD_OPPTY_BULK(i).PARENT_OPPTY_NUMBER,
    CHILD_OPPTY_BULK(i).OPPTY_NUMBER,
    CHILD_OPPTY_BULK(i).TYPE,
    CHILD_OPPTY_BULK(i).OPPTY_NAME,
    CHILD_OPPTY_BULK(i).MILLION_PLUS_HEADER_LTR_FLAG,
    CHILD_OPPTY_BULK(i).INCLUDED_FLAG,
    CHILD_OPPTY_BULK(i).DESIGN_WIN_DATE,
    CHILD_OPPTY_BULK(i).DW_FISCAL_YEAR,
    CHILD_OPPTY_BULK(i).DW_FISCAL_QTR,
    CHILD_OPPTY_BULK(i).PARENT_DW_FY_YEAR ,
    CHILD_OPPTY_BULK(i).PARENT_DW_FY_QTR,
    CHILD_OPPTY_BULK(i).PRODUCTION_DATE,
    CHILD_OPPTY_BULK(i).PROD_FISCAL_YEAR,
    CHILD_OPPTY_BULK(i).PROD_FISCAL_QTR,
    CHILD_OPPTY_BULK(i).PARENT_PROD_FISCAL_YEAR,
    CHILD_OPPTY_BULK(i).PARENT_PROD_FISCAL_QTR,
    CHILD_OPPTY_BULK(i).MARKET_SEGMENT,
    CHILD_OPPTY_BULK(i).REGION,
    CHILD_OPPTY_BULK(i).PARENT_REGION,
    CHILD_OPPTY_BULK(i).STAGE,
    CHILD_OPPTY_BULK(i).PARENT_STAGE,
    CHILD_OPPTY_BULK(i).STATUS,
    CHILD_OPPTY_BULK(i).PARENT_STATUS,
    CHILD_OPPTY_BULK(i).BU,
    CHILD_OPPTY_BULK(i).DIVISION,
    CHILD_OPPTY_BULK(i).PRODUCT_LINE,
    CHILD_OPPTY_BULK(i).SUB_PRODUCT_LINE,
    CHILD_OPPTY_BULK(i).FINANCIAL_GROUP,
    CHILD_OPPTY_BULK(i).PART_NUMBER,
    CHILD_OPPTY_BULK(i).PRODUCT_FAMILY,
    CHILD_OPPTY_BULK(i).DEVICE,
    CHILD_OPPTY_BULK(i).REASON_FOR_EXCLUSION,
    CHILD_OPPTY_BULK(i).LTR,
    CHILD_OPPTY_BULK(i).PRIMARY_OPPTY_OWNER,
    CHILD_OPPTY_BULK(i).CUSTOMER,
    CHILD_OPPTY_BULK(i).SOURCE_END_CUSTOMER,
    CHILD_OPPTY_BULK(i).TIER1_CUSTOMER,
    CHILD_OPPTY_BULK(i).DW_CONFIDENCE,
    CHILD_OPPTY_BULK(i).PROGRAM_NAME,
    CHILD_OPPTY_BULK(i).APPLICATION_SEGMENT,
    CHILD_OPPTY_BULK(i).NETWORK_PROCESSOR,
    CHILD_OPPTY_BULK(i).DEVELOPMENT_STAGE,
    CHILD_OPPTY_BULK(i).ITEM_TYPE_GROUP,
    CHILD_OPPTY_BULK(i).OPPTY_ID,
    CHILD_OPPTY_BULK(i).TIER1_CUSTOMER_FILTER,
    CHILD_OPPTY_BULK(i).TIER1_REGION);
    END LOOP;
END IF;

OPEN C_PARENT_OPPTY_ATTRIBUTES;
FETCH C_PARENT_OPPTY_ATTRIBUTES BULK COLLECT INTO UPDATE_BULK;
CLOSE C_PARENT_OPPTY_ATTRIBUTES;

IF UPDATE_BULK.count > 0 THEN
   FOR i IN UPDATE_BULK.first..UPDATE_BULK.last LOOP
            UPDATE EDW1.DW_SF_PARENT_CHILD_OPPTY_F
            SET
                PARENT_DW_FY_YEAR = UPDATE_BULK(i).dw_fiscal_year,
                PARENT_DW_FY_QTR = UPDATE_BULK(i).dw_fiscal_qtr,
                PARENT_ONE_MIL_LTR_PLUS_FLAG= UPDATE_BULK(i). MILLION_PLUS_HEADER_LTR_FLAG,
                PARENT_PROD_FISCAL_YEAR = UPDATE_BULK(i).prod_fiscal_year,
                PARENT_PROD_FISCAL_QTR = UPDATE_BULK(i).prod_fiscal_qtr,
                PARENT_INCLUDED_FLAG=UPDATE_BULK(i).included_flag,
                PARENT_STAGE = UPDATE_BULK(i).STAGE,
                PARENT_STATUS = UPDATE_BULK(i).STATUS,
                PARENT_REGION = UPDATE_BULK(i).REGION
               WHERE
                parent_oppty_number = UPDATE_BULK(i).oppty_number and type = 'Child';

        END LOOP;
    END IF;
COMMIT;
END;

--- procedure 6